service: test-pure-lambda

custom:
  service:
    name: log-group-issue-lambda

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false

package:
  individually: true

functions:
  myFunction:
    name: ${self:custom.service.name}-myFunction
    handler: index.handler
  myFunction2:
    handler: index.handler

plugins:
  - serverless-plugin-reducer
