service: test-http-api

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false

package:
  individually: true

functions:
  function:
    handler: index.handler

resources:
  Resources:
    FunctionLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Fn::GetAtt:
            - FunctionLambdaFunction
            - Arn
        Action: lambda:InvokeFunction
        Principal: apigateway.amazonaws.com
        SourceArn: arn:aws:execute-api:us-east-1:992311060759:u4rze1xtf5/*/*/*

plugins:
  - serverless-plugin-reducer
