service: test-event-bridge-lambda

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false

package:
  individually: true

functions:
  myFunction:
    handler: index.handler
    events:
      - eventBridge:
          schedule: rate(7 days)
          input:
            key1: value1

plugins:
  - serverless-plugin-reducer
