service: test-api-gw-logs

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: dev
  versionFunctions: false
  logs:
    restApi: true
    frameworkLambda: true

package:
  individually: true

functions:
  myFunction:
    handler: index.handler
    events:
      - http:
          path: foo
          method: GET

plugins:
  - serverless-plugin-reducer
