service: test-7551

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false

resources:
  Resources:
    EventHandlingEventBridgeRuleDataProviderError:
      Type: AWS::Events::Rule
      Properties:
        Description: "Rule to handle the data provider errors from SSI"
        EventBusName: !Ref EventHandlingEventBridgeBus
        EventPattern:
          {
            "source":
              [
                { "prefix": "inflection.searchservice." },
                { "prefix": "inflection.hiringtask." },
                { "prefix": "inflection.safedecisionasync." },
              ],
            "detail-type": ["DataProviderResponseLog"],
            "detail": { "IsError": [true] },
          }
        Name: !Sub data-provider-error-rule-${opt:stage, self:provider.stage}
        Targets:
          - Arn: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:process-data-provider-error
            Id: process-data-provider-error
