service: test-api-gw

provider:
  name: aws
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - apigateway:PATCH
      Resource:
        - arn:aws:apigateway:*::/account
    - Effect: Allow
      Action:
        - iam:PassRole
      Resource:
        - arn:aws:iam::*:role/*

package:
  individually: true

functions:
  myFunction:
    handler: index.handler
    events:
      - http:
          path: foo
          method: GET
  myFunction2:
    handler: index.handler

plugins:
  - serverless-plugin-reducer

resources:
  Resources:
    ApiGatewayAccount:
      Type: "AWS::ApiGateway::Account"
