service: test-lambda-s3-custom

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false
  s3:
    testCustomBucket:
      name: test-custom-bucket
      versioningConfiguration:
        Status: Enabled

package:
  individually: true

functions:
  function:
    handler: index.handler
    events:
      - s3: testCustomBucket

plugins:
  - serverless-plugin-reducer
