service: test-http-api-export

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false

resources:
  Resources:
    HttpApi:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: dev-test-http-api-export
        ProtocolType: HTTP
    HttpApiStage:
      Type: AWS::ApiGatewayV2::Stage
      Properties:
        ApiId:
          Ref: HttpApi
        StageName: $default
        AutoDeploy: true
  Outputs:
    HttpApiId:
      Value:
        Ref: HttpApi
      Export:
        Name: TestHttpApiExportId
