service: test-issue-8576

provider:
  name: aws
  region: us-east-2

package:
  artifact: ${opt:artifact, ''}

layers:
  my-lambda-layer:
    path: dist
    description: xxx
    compatibleRuntimes:
      - nodejs12.x
    retain: true
