service: test-api-gw

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false

package:
  individually: true

functions:
  function:
    handler: index.handler
    events:
      - http:
          path: foo
          method: GET
          integration: lambda
          response:
            statusCodes:
              200:
                pattern: '.*"statusCode":200,.*' # JSON response
                template: $input.path("$.body") # JSON return object
              400:
                pattern: '.*"statusCode":400,.*' # JSON response
                template: $input.path("$.errorMessage") # JSON return object
              404:
                pattern: '.*"statusCode":404,.*' # JSON response
                template: $input.path("$.errorMessage") # JSON return object
              500:
                pattern: '.*"statusCode":500,.*' # JSON response
                template: $input.path("$.errorMessage") # JSON return object

plugins:
  - serverless-plugin-reducer
