service: test-issue-7994

custom:
  stage: ${opt:stage, self:provider.stage}
  accountId: 992311060759
  eventBus: arn:aws:events:${self:provider.region}:${self:custom.accountId}:event-bus/${self:custom.stage}

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: dev
  versionFunctions: false

functions:
  main:
    handler: handler.hello
    timeout: 30
    memorySize: 256
    events:
      - eventBridge:
          eventBus: ${self:custom.eventBus}
          pattern:
            detail:
              test:
                - arst
