service: test-custom-role-with-eb

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false
  role: arn:aws:iam::992311060759:role/test-custom-role

package:
  individually: true

functions:
  myFunction:
    handler: index.handler
    events:
      - http:
          path: foo
          method: GET
      - eventBridge:
          schedule: rate(7 days)
          input:
            key1: value1

plugins:
  - serverless-plugin-reducer
