service: test-7206

provider:
  name: aws
  runtime: nodejs12.x
  stage: "${opt:stage, self:custom.defaults.stage}"
  profile: "${self:custom.profiles.${self:provider.stage}}"
  environment:
    APIG_ENDPOINT:
      Fn::Join:
        - ""
        - - Ref: WebsocketsApi
          - .execute-api.
          - Ref: AWS::Region
          - .amazonaws.com/
          - ${self:provider.stage}
custom:
  defaults:
    stage: local
  profiles:
    local: "${self:service}-local"
    dev: "${self:service}-dev"

functions:
  # region WebSockets
  ws-connection-handler:
    handler: index.js
    events:
      - websocket:
          route: $connect

      - websocket:
          route: message

      - websocket:
          route: $default

      - websocket:
          route: $disconnect
