service: test-knative
provider:
  name: knative
  # TODO: Complete configuration
  docker:
    username: foo

package:
  individually: true

functions:
  function:
    handler: index.handler

plugins:
  - serverless-plugin-reducer
  - serverless-knative
