service: test-1

custom:
  service:
    name: log-group-issue-lambda

provider:
  name: aws
  runtime: nodejs10.x

package:
  individually: true

functions:
  myFunction:
    name: ${self:custom.service.name}-myFunction
    handler: index.handler
  myFunction2:
    handler: index.handler
    events:
      - http:
          integration: lambda
          path: sample-api
          method: get

plugins:
  - serverless-plugin-reducer
