service: test-custom-provider

provider:
  name: custom

package:
  individually: true

functions:
  function:
    handler: index.handler
    events:
      - http:
          foo: bar

plugins:
  - ./provider-plugin
  - serverless-plugin-reducer
