service: test-api-gw

provider:
  name: aws
  runtime: nodejs10.x
  apiGateway:
    restApiId: test-api-gw-custom-id

package:
  individually: true

functions:
  myFunction:
    handler: index.handler
  myFunction2:
    handler: index.handler

plugins:
  - serverless-plugin-reducer
