service: test-api-lambda-authorizer

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false

package:
  individually: true

functions:
  authorize:
    name: bar-authorize
    handler: index.handler
  function:
    handler: index.handler
    events:
      - http:
          path: foo
          method: GET
          authorizer: authorize

plugins:
  - serverless-plugin-reducer
