service: test-http-api

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false

package:
  individually: true

functions:
  function:
    handler: index.handler
    provisionedConcurrency: 1
  other:
    handler: other.handler

resources:
  Resources:
    FunctionLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Fn::Join:
            - ":"
            - - Fn::GetAtt:
                  - FunctionLambdaFunction
                  - Arn
              - provisioned
        Action: lambda:InvokeFunction
        Principal: apigateway.amazonaws.com
        SourceArn: arn:aws:execute-api:us-east-1:992311060759:*/*
      DependsOn: FunctionProvConcLambdaAlias
    OtherLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Fn::GetAtt:
            - OtherLambdaFunction
            - Arn
        Action: lambda:InvokeFunction
        Principal: apigateway.amazonaws.com
        SourceArn: arn:aws:execute-api:us-east-1:992311060759:*/*

plugins:
  - serverless-plugin-reducer
