service: test-regular-lambda

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false

package:
  individually: true

functions:
  myFunction:
    handler: index.handler

plugins:
  - serverless-plugin-reducer
