service: test-invalid-deploy

custom:
  service:
    name: log-group-issue-lambda

provider:
  name: aws
  runtime: nodejs10.x

package:
  individually: true

functions:
  myFunction:
    name: ${self:custom.service.name}-myFunction
    handler: index.handler
    events:
      - http: PO /foo
  myFunction2:
    handler: index.handler

plugins:
  - serverless-plugin-reducer
