service: test-api-lambda-authorizer-${opt:prefix}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false

package:
  individually: true

functions:
  authorize:
    name: authorize-${opt:prefix}
    handler: index.handler
  function:
    name: function-${opt:prefix}
    handler: index.handler
    events:
      - http:
          path: /${opt:prefix}/test
          method: GET
          authorizer: authorize

plugins:
  - serverless-plugin-reducer
