service: test-api-gw-shared-other-sls-stage

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: other
  versionFunctions: false
  apiGateway:
    restApiId: pkhriceyzl
    restApiRootResourceId: 1xufji4tak

package:
  individually: true

functions:
  myFunction:
    handler: index.handler
    events:
      - http:
          path: bar3
          method: GET

plugins:
  - serverless-plugin-reducer
