service: test-api-gw

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1

package:
  individually: true

functions:
  myFunction:
    handler: index.handler
    events:
      - http:
          path: foo
          method: GET
  myFunction2:
    handler: index.handler

plugins:
  - serverless-plugin-reducer
