service: test-lambda-destinations

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false

package:
  individually: true

functions:
  function:
    handler: index.handler
    destinations:
      onSuccess: arn:aws:lambda:us-east-1:992311060759:function:test-http-api-dev-function

plugins:
  - serverless-plugin-reducer
