service: test-websockets-lambda

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false
  apiGateway:
    websocketApiId: n8iksi4odi

package:
  individually: true

functions:
  myFunction:
    handler: index.handler
  myFunction2:
    handler: index.handler
    events:
      - websocket: $default

plugins:
  - serverless-plugin-reducer
