service: test-api-gw-provisioned-concurrency

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false
  logs:
    restApi: true

package:
  individually: true

functions:
  myFunction:
    handler: index.handler
    provisionedConcurrency: 3
    events:
      - http:
          path: foo
          method: GET

plugins:
  - serverless-plugin-reducer
