service: test-custom-iam-managed-policies

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/AdministratorAccess

package:
  individually: true

functions:
  function:
    handler: index.handler

plugins:
  - serverless-plugin-reducer
