service: test-api-gw-export-shared-with-lambdas

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false
  tracing:
    apiGateway: true

package:
  individually: true

functions:
  myFunction:
    handler: index.handler
    events:
      - http:
          path: core
          method: GET

plugins:
  - serverless-plugin-reducer

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: CfExportedApiGwWithLambdas

  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: CfExportedApiGwWithLambdas-restApiId
    apiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - ApiGatewayRestApi
          - RootResourceId
      Export:
        Name: CfExportedApiGwWithLambdas-rootResourceId
