service: test-api-gw-api-keys

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false
  apiKeys:
    # TODO: Replace with valid one
    - name: someKey
      value: someKey

package:
  individually: true

functions:
  function:
    handler: index.handler
    events:
      - http:
          path: foo
          method: GET
      - http:
          path: foo
          method: POST

plugins:
  - serverless-plugin-reducer
