service: test-api-websockets-logs

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  versionFunctions: false
  logs:
    websocket: true

package:
  individually: true

functions:
  myFunction:
    handler: index.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default

plugins:
  - serverless-plugin-reducer
