service: test-custom-role-lambda

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false
  role: arn:aws:iam::992311060759:role/test-custom-role
  logs:
    restApi: true

package:
  individually: true

functions:
  myFunction:
    handler: index.handler
    events:
      - http:
          path: foo
          method: GET

plugins:
  - serverless-plugin-reducer
