service: test-7189

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  tracing:
    lambda: true
    apiGateway: true

functions:
  function:
    handler: index.handler
    events:
      - http:
          path: foo
          method: GET
          cors: true
  functionB:
    handler: index.handler
    events:
      - http:
          path: foo
          method: GET
          cors: true
