service: test-7357

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stackName: test-7357-${self:provider.stage}
  stage: dev
  versionFunctions: false
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - Ref: ServerlessDeploymentBucket

package:
  individually: true

functions:
  function:
    handler: index.handler

plugins:
  - serverless-plugin-reducer
