service: test-custom-provider

provider:
  name: custom
  foo: bar
  elo: mar

package:
  individually: true

functions:
  function:
    handler: index.handler
    events:
      - alb:
          test: "fsdf"

plugins:
  - ./provider-plugin
  - serverless-plugin-reducer
