service: test-api-gw-export-shared

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false

resources:
  Resources:
    CfExportedApiGw:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: CfExportedApiGw

  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: CfExportedApiGw
      Export:
        Name: CfExportedApiGw-restApiId
    apiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - CfExportedApiGw
          - RootResourceId
      Export:
        Name: CfExportedApiGw-rootResourceId
