service: test-knative
provider:
  name: knative
  # TODO: Complete configuration
  docker:
    username: foo

package:
  individually: true

plugins:
  - serverless-plugin-reducer
  - serverless-knative
