service: test-knative
provider:
  name: knative

functionTwo:
  events:
    - cron:
        schedule: "* * * * *"
        data: '{"message": "Hello world from a Cron event source!"}'

plugins:
  - serverless-knative
