service: test-offline-lambda

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false

package:
  individually: true

functions:
  myFunction:
    handler: index.handler
    events:
      - http:
          path: test-get
          method: get
  myFunction2:
    handler: index.handler

plugins:
  - serverless-offline
  - serverless-plugin-reducer
