service: test-variables-custom

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false

plugins:
  - ./plugin

custom:
  var1: ${echo:foo bar1}
  var2: ${echo:"foo bar2"}
  var3: ${echo:'foo bar3'}
