service: test-custom-deployment-bucket

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false
  deploymentBucket:
    name: test-custom-bucket

package:
  individually: true

functions:
  myFunction:
    handler: index.handler

plugins:
  - serverless-plugin-reducer
