service: test-dashboard-api-gateway-export

org: medikoo
app: medikoo-test

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev

resources:
  Resources:
    CfExportedDashboardApiGw:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: CfExportedDashboardApiGw

  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: CfExportedDashboardApiGw
      Export:
        Name: CfExportedDashboardApiGw-restApiId
    apiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - CfExportedDashboardApiGw
          - RootResourceId
      Export:
        Name: CfExportedDashboardApiGw-rootResourceId
