service: test-http-api-catch-all

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false

package:
  individually: true

functions:
  function:
    handler: index.handler
    provisionedConcurrency: 1
    events:
      - httpApi: "*"

  other:
    handler: other.handler
    events:
      - httpApi:
          method: "*"
          path: /foo

plugins:
  - serverless-plugin-reducer
