service: test-custom-package-path

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false

package:
  individually: true
  path: custom-package-path

functions:
  myFunction:
    handler: index.handler

plugins:
  - serverless-plugin-reducer
