service: test-lambda-kinesis

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false

package:
  individually: true

functions:
  function:
    handler: index.handler
    events:
      - stream:
          type: kinesis
          arn: arn:aws:kinesis:us-east-1:992311060759:stream/test

plugins:
  - serverless-plugin-reducer
