service: test-variables-ssm

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false

custom:
  user:
    myArrayVar: ${ssm:stringList~split}

package:
  individually: true

plugins:
  - serverless-plugin-reducer
