service: test-variables

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false

custom:
  user:
    with_yaml_password: ${file(./config/example.yml):user.password2,"abcdefg"}

package:
  individually: true

plugins:
  - serverless-plugin-reducer
