service: test-function-artifact

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false

package:
  individually: true

functions:
  fn1:
    handler: index.handler
    package:
      artifact: first/handler.zip
  fn2:
    handler: index.handler
    package:
      artifact: second/handler.zip
