service: test-sqs-lambda

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false

package:
  individually: true

plugins:
  - serverless-plugin-reducer

functions:
  function:
    handler: index.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:992311060759:test-queue-1
