service: test-dashboard-plugin

tenant: medikoo
app: medikoo-test

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: dev
  versionFunctions: false

package:
  individually: true

functions:
  myFunction:
    handler: index.handler

plugins:
  - serverless-plugin-reducer
