service: test-api-gw-tags

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: dev
  versionFunctions: false
  tags:
    foo: "bar"

package:
  individually: true

functions:
  myFunction:
    handler: index.handler
    events:
      - http:
          path: foo
          method: GET

plugins:
  - serverless-plugin-reducer
