service: test-event-bridge

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev

resources:
  Resources:
    TestEventBridge:
      Type: AWS::Events::EventBus
      Properties:
        Name: test-standalone
  Outputs:
    TestEventBridge:
      Value:
        Ref: TestEventBridge
