service: test-tagged-lambda

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false
  tags:
    foo: bar

package:
  individually: true

functions:
  function:
    handler: index.handler

plugins:
  - serverless-plugin-reducer
