service: test-api-gw

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false

package:
  individually: true

functions:
  authorize:
    name: ${opt:prefix}-authorize # function name & patched authorizer name
    handler: index.handler
  myFunction:
    handler: index.handler
    events:
      - http:
          path: foo
          method: GET

plugins:
  - serverless-plugin-reducer
