service: test-websockets-lambda

provider:
  name: aws
  runtime: nodejs10.x
  websocketsApiName: custom-websockets-api-name
  websocketsApiRouteSelectionExpression: $request.body.action
  versionFunctions: false

package:
  individually: true

functions:
  myFunction:
    handler: index.handler
  myFunction2:
    handler: index.handler
    events:
      - websocket: $default

plugins:
  - serverless-plugin-reducer
