service: test-cognito-user-pool-existing

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: dev
  versionFunctions: false

package:
  individually: true

functions:
  function:
    handler: index.handler
    events:
      - cognitoUserPool:
          pool: test-pool
          trigger: PostConfirmation
          existing: true

plugins:
  - serverless-plugin-reducer
