service: test-regular-lambda

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false

functions:
  function:
    handler: index.handler
    events:
      - cloudFront:
          eventType: viewer-response
          # TODO: Change with valid one
          origin: s3://bucketname.s3.amazonaws.com/files
