service: test-api-lambda-authorizer

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false

package:
  individually: true

plugins:
  - serverless-plugin-reducer


functions:
  authorize:
    handler: index.handler
  function:
    handler: index.handler
    events:
      - http:
          path: /test
          method: GET
          authorizer: authorize
