service: test-http-api-shared

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false
  httpApi:
    id: odpcs1ujgl

package:
  individually: true

functions:
  function:
    handler: index.handler
    # provisionedConcurrency: 1 # Increases significantly test time
    events:
      - httpApi:
          method: GET
          path: /foo
      - httpApi:
          method: POST
          path: /some-post

  other:
    handler: other.handler
    events:
      - httpApi:
          method: get
          path: /bar/{marko}

plugins:
  - serverless-plugin-reducer
