service: test-api-gw-integration-creds

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false

package:
  individually: true

functions:
  function:
    handler: index.handler
    events:
      - http:
          path: foo
          method: GET
          authorizer: aws_iam

plugins:
  - serverless-plugin-reducer

resources:
  Resources:
    ApiGatewayMethodFooGet:
      Type: AWS::ApiGateway::Method
      Properties:
        Integration:
          Credentials: "arn:aws:iam::*:user/*"
