service: test-lambda-dynamodb

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: dev
  versionFunctions: false

package:
  individually: true

functions:
  function:
    handler: index.handler
    events:
      - stream:
          type: dynamodb
          arn: arn:aws:dynamodb:us-east-1:992311060759:table/test/stream/2020-04-28T11:44:21.697

plugins:
  - serverless-plugin-reducer
