service: test-websocket-lambda

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false
  environment:
    APIG_ENDPOINT:
      Fn::Join:
        - ""
        - - Ref: WebsocketsApi
          - .execute-api.
          - Ref: AWS::Region
          - .amazonaws.com/
          - ${self:provider.stage}

package:
  individually: true

functions:
  function:
    handler: index.handler
    events:
      - websocket: $default

plugins:
  - serverless-plugin-reducer
