service: test-lambda-for-s3-events

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false

package:
  individually: true

functions:
  function:
    handler: index.handler
    events:
      - s3: test-for-s3-events

plugins:
  - serverless-plugin-reducer
