service: test-http-api-authorizer

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false
  httpApi:
    cors:
      allowedOrigins: "https://medikoo.com"
      exposedResponseHeaders: "X-Amz-Date"
      maxAge: 60
    authorizers:
      someAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_Vx8SkSqD9
        audience: 6closm6qthugjsuanu1mk1s62i

package:
  individually: true

functions:
  function:
    handler: index.handler
    # provisionedConcurrency: 1 # Increases significantly test time
    events:
      - httpApi:
          method: GET
          path: /foo
      - httpApi:
          method: POST
          path: /some-post
          authorizer: someAuthorizer

  other:
    handler: other.handler
    events:
      - httpApi:
          method: get
          path: /bar/{marko}

plugins:
  - serverless-plugin-reducer
