service: test-api-gw

provider:
  name: aws
  stage: other
  runtime: nodejs10.x
  region: us-east-1
  versionFunctions: false

package:
  individually: true

functions:
  myFunction:
    handler: index.handler
    events:
      - http:
          path: foo
          method: GET

plugins:
  - serverless-plugin-reducer
