service: test-7357

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  stackName: Test-7357-${self:provider.stage}
  versionFunctions: false

package:
  individually: true

functions:
  function:
    handler: index.handler

plugins:
  - serverless-plugin-reducer
