service: test-dashboard-python-lambda

org: medikoo
app: medikoo-test

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: dev
  versionFunctions: false

functions:
  function:
    handler: handler.hello
