service: test-issue-7635

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  versionFunctions: false
  deploymentBucket: serverless-custom-bucket

package:
  individually: true

plugins:
  - serverless-plugin-reducer

resources:
  Resources:
    TestBucket:
      Type: AWS::S3::Bucket
      Properties:
        LifecycleConfiguration:
          Rules:
            - ExpirationInDays: three
              Prefix: "/"
              Status: Enabled
