service: test-api-gw-shared

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false
  apiGateway:
    restApiId:
      "Fn::ImportValue": CfExportedApiGw-restApiId
    restApiRootResourceId:
      "Fn::ImportValue": CfExportedApiGw-rootResourceId
  logs:
    restApi: true

package:
  individually: true

functions:
  myFunction:
    handler: index.handler
    events:
      - http:
          path: bar
          method: GET
  myFunction2:
    handler: index.handler

plugins:
  - serverless-plugin-reducer
