app: my-app
service: my-service
plugins:
  - ./my-plugin
  - serverless-plugin-reducer
  
package:
  individually: true
  
provider:
  name: aws
  runtime: nodejs12.x
  stackName: ${self:app}-${self:provider.stage}-${self:service}
  stage: dev
functions:
  hello:
    handler: index.handler

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${foo:bar}