service: test-pure-lambda

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false

package:
  individually: true

functions:
  myFunction:
    handler: index.handler
  myFunction2:
    name: test-pure-lambda-${self:provider.region}-myFunction2
    handler: index.handler

plugins:
  - serverless-plugin-reducer
